# © 2026 urdekcah. Все права защищены.
# Лицензировано в соответствии с условиями AGPL-3.0
"""Offline Russian to Korean translation for Apple Silicon."""

from perevod.config import DEFAULT_MODEL_ID, MODEL_ENV_VAR, resolve_model_id
from perevod.dataset import (
    DEFAULT_SPLIT_DIR,
    MANIFEST_FILENAME,
    TEST_FILENAME,
    TRAIN_FILENAME,
    VALID_FILENAME,
    DatasetError,
    RecordShapeError,
    SchemaError,
    SplitLayoutError,
    SplitReport,
    build_training_record,
    classify_record,
    parse_training_record,
    prompt_shape_fingerprint,
    validate_schema,
    validate_split_dir,
    validate_training_file,
)
from perevod.prepare import (
    InputError,
    OutputExistsError,
    OutputPathError,
    PrepareConfig,
    PrepareError,
    PrepareResult,
    prepare_splits,
    render_report,
)
from perevod.training import (
    DEFAULT_ADAPTER_ROOT,
    DEFAULT_RUN_NAME,
    AdapterExistsError,
    AdapterPathError,
    TrainerFailedError,
    TrainingConfig,
    TrainingError,
    build_argv,
    resolve_adapter_path,
    train_adapter,
)
from perevod.translator import Translator

__all__ = [
    "DEFAULT_ADAPTER_ROOT",
    "DEFAULT_MODEL_ID",
    "DEFAULT_RUN_NAME",
    "DEFAULT_SPLIT_DIR",
    "MANIFEST_FILENAME",
    "MODEL_ENV_VAR",
    "TEST_FILENAME",
    "TRAIN_FILENAME",
    "VALID_FILENAME",
    "AdapterExistsError",
    "AdapterPathError",
    "DatasetError",
    "InputError",
    "OutputExistsError",
    "OutputPathError",
    "PrepareConfig",
    "PrepareError",
    "PrepareResult",
    "RecordShapeError",
    "SchemaError",
    "SplitLayoutError",
    "SplitReport",
    "TrainerFailedError",
    "TrainingConfig",
    "TrainingError",
    "Translator",
    "build_argv",
    "build_training_record",
    "classify_record",
    "parse_training_record",
    "prepare_splits",
    "prompt_shape_fingerprint",
    "render_report",
    "resolve_adapter_path",
    "resolve_model_id",
    "train_adapter",
    "validate_schema",
    "validate_split_dir",
    "validate_training_file",
]
